import type { Locale } from "./i18n";

export type ConverterCopy = { choose: string; addMore: string; converting: string; prompt: string; limit: string; processing: string; privacy: string; converted: string; download: string; remove: string; reset: string; zip: string; zipBuilding: string; tooMany: (max: number) => string; truncated: string; invalid: (count: number) => string; oversized: (count: number) => string; failed: (count: number) => string; pixels: string };

export const converterCopy: Record<Locale, ConverterCopy> = {
  ko: { choose: "JPG 파일 선택", addMore: "파일 더 추가", converting: "변환 중…", prompt: "JPG 이미지를 여기에 놓거나 선택하세요", limit: "JPG · JPEG · 파일당 최대 30MB", processing: "브라우저에서 안전하게 처리 중", privacy: "파일은 서버로 전송되지 않고 브라우저 안에서 처리됩니다.", converted: "개 변환 완료", download: "다운로드", remove: "삭제", reset: "전체 지우기", zip: "전체 ZIP", zipBuilding: "ZIP 생성 중…", tooMany: (max) => `한 번에 최대 ${max}개까지 변환할 수 있습니다.`, truncated: "최대 10개까지만 선택했습니다.", invalid: (count) => `JPG가 아닌 파일 ${count}개를 제외했습니다.`, oversized: (count) => `30MB를 넘는 파일 ${count}개를 제외했습니다.`, failed: (count) => `${count}개 파일을 변환하지 못했습니다. 다른 JPG 파일로 다시 시도해 주세요.`, pixels: "px" },
  en: { choose: "Choose JPG files", addMore: "Add more files", converting: "Converting…", prompt: "Drop JPG images here or choose files", limit: "JPG · JPEG · up to 30MB per file", processing: "Processing securely in your browser", privacy: "Your files are processed in your browser and never sent to our server.", converted: " converted", download: "Download", remove: "Remove", reset: "Clear all", zip: "Download ZIP", zipBuilding: "Creating ZIP…", tooMany: (max) => `You can convert up to ${max} files at a time.`, truncated: "Only the first 10 files were selected.", invalid: (count) => `${count} non-JPG file(s) were excluded.`, oversized: (count) => `${count} file(s) over 30MB were excluded.`, failed: (count) => `${count} file(s) could not be converted. Please try another JPG file.`, pixels: "px" },
  ja: { choose: "JPGファイルを選択", addMore: "ファイルを追加", converting: "変換中…", prompt: "JPG画像をドロップするか選択してください", limit: "JPG · JPEG · 1ファイル最大30MB", processing: "ブラウザで安全に処理しています", privacy: "ファイルはサーバーに送信されず、ブラウザ内で処理されます。", converted: "件変換完了", download: "ダウンロード", remove: "削除", reset: "すべてクリア", zip: "ZIPをダウンロード", zipBuilding: "ZIP作成中…", tooMany: (max) => `一度に${max}ファイルまで変換できます。`, truncated: "最初の10ファイルのみ選択しました。", invalid: (count) => `JPG以外のファイル${count}件を除外しました。`, oversized: (count) => `30MBを超えるファイル${count}件を除外しました。`, failed: (count) => `${count}件の変換に失敗しました。別のJPGでお試しください。`, pixels: "px" },
  zh: { choose: "选择 JPG 文件", addMore: "添加更多文件", converting: "转换中…", prompt: "将 JPG 图片拖到此处或选择文件", limit: "JPG · JPEG · 每个文件最大 30MB", processing: "正在浏览器中安全处理", privacy: "文件仅在浏览器中处理，不会上传到服务器。", converted: " 个已转换", download: "下载", remove: "移除", reset: "全部清除", zip: "下载 ZIP", zipBuilding: "正在创建 ZIP…", tooMany: (max) => `一次最多可转换 ${max} 个文件。`, truncated: "仅选择了前 10 个文件。", invalid: (count) => `已排除 ${count} 个非 JPG 文件。`, oversized: (count) => `已排除 ${count} 个超过 30MB 的文件。`, failed: (count) => `${count} 个文件转换失败，请尝试其他 JPG 文件。`, pixels: "像素" },
  "zh-tw": { choose: "選擇 JPG 檔案", addMore: "新增更多檔案", converting: "轉換中…", prompt: "將 JPG 圖片拖曳至此處或選擇檔案", limit: "JPG · JPEG · 每個檔案最大 30MB", processing: "正在瀏覽器中安全處理", privacy: "檔案只在瀏覽器中處理，不會上傳至伺服器。", converted: " 個已轉換", download: "下載", remove: "移除", reset: "全部清除", zip: "下載 ZIP", zipBuilding: "正在建立 ZIP…", tooMany: (max) => `一次最多可轉換 ${max} 個檔案。`, truncated: "僅選擇了前 10 個檔案。", invalid: (count) => `已排除 ${count} 個非 JPG 檔案。`, oversized: (count) => `已排除 ${count} 個超過 30MB 的檔案。`, failed: (count) => `${count} 個檔案轉換失敗，請嘗試其他 JPG 檔案。`, pixels: "像素" },
  de: { choose: "JPG-Dateien auswählen", addMore: "Weitere Dateien", converting: "Wird konvertiert…", prompt: "JPG-Bilder hier ablegen oder Dateien auswählen", limit: "JPG · JPEG · max. 30 MB pro Datei", processing: "Sicher in Ihrem Browser verarbeitet", privacy: "Ihre Dateien werden im Browser verarbeitet und nie an unseren Server gesendet.", converted: " konvertiert", download: "Herunterladen", remove: "Entfernen", reset: "Alle löschen", zip: "ZIP herunterladen", zipBuilding: "ZIP wird erstellt…", tooMany: (max) => `Sie können bis zu ${max} Dateien gleichzeitig konvertieren.`, truncated: "Nur die ersten 10 Dateien wurden ausgewählt.", invalid: (count) => `${count} Nicht-JPG-Datei(en) wurden ausgeschlossen.`, oversized: (count) => `${count} Datei(en) über 30 MB wurden ausgeschlossen.`, failed: (count) => `${count} Datei(en) konnten nicht konvertiert werden.`, pixels: "px" },
  fr: { choose: "Choisir des fichiers JPG", addMore: "Ajouter des fichiers", converting: "Conversion…", prompt: "Déposez vos images JPG ou choisissez des fichiers", limit: "JPG · JPEG · 30 Mo maximum par fichier", processing: "Traitement sécurisé dans votre navigateur", privacy: "Vos fichiers sont traités dans votre navigateur et ne sont jamais envoyés à notre serveur.", converted: " converti(s)", download: "Télécharger", remove: "Supprimer", reset: "Tout effacer", zip: "Télécharger le ZIP", zipBuilding: "Création du ZIP…", tooMany: (max) => `Vous pouvez convertir jusqu’à ${max} fichiers à la fois.`, truncated: "Seuls les 10 premiers fichiers ont été sélectionnés.", invalid: (count) => `${count} fichier(s) non JPG exclu(s).`, oversized: (count) => `${count} fichier(s) de plus de 30 Mo exclu(s).`, failed: (count) => `${count} fichier(s) n’ont pas pu être converti(s).`, pixels: "px" },
  es: { choose: "Elegir archivos JPG", addMore: "Añadir más archivos", converting: "Convirtiendo…", prompt: "Suelta imágenes JPG aquí o elige archivos", limit: "JPG · JPEG · máximo 30 MB por archivo", processing: "Procesando de forma segura en tu navegador", privacy: "Tus archivos se procesan en el navegador y nunca se envían a nuestro servidor.", converted: " convertido(s)", download: "Descargar", remove: "Eliminar", reset: "Borrar todo", zip: "Descargar ZIP", zipBuilding: "Creando ZIP…", tooMany: (max) => `Puedes convertir hasta ${max} archivos a la vez.`, truncated: "Solo se seleccionaron los 10 primeros archivos.", invalid: (count) => `Se excluyeron ${count} archivo(s) que no son JPG.`, oversized: (count) => `Se excluyeron ${count} archivo(s) de más de 30 MB.`, failed: (count) => `No se pudieron convertir ${count} archivo(s).`, pixels: "px" },
};

export const homeCopy: Record<Locale, { language: string; eyebrow: string; title: string; accent: string; description: string; cta: string; tools: string; privacy: string }> = {
  ko: { language: "한국어", eyebrow: "OneDay Tools · All in One Tool", title: "파일 작업을 한곳에서", accent: "더 간단하게.", description: "이미지·PDF·오디오 도구를 설치 없이 브라우저에서 바로 처리하세요.", cta: "JPG PNG 변환 시작", tools: "인기 이미지 도구", privacy: "파일은 브라우저 안에서 안전하게 처리됩니다." },
  en: { language: "English", eyebrow: "OneDay Tools · All in One Tool", title: "Handle files in one place", accent: "Keep it simple.", description: "Convert and manage images, PDFs, and audio right in your browser—no install required.", cta: "Start JPG to PNG", tools: "Popular image tools", privacy: "Your files are processed securely in your browser." },
  ja: { language: "日本語", eyebrow: "OneDay Tools · All in One Tool", title: "ファイル作業をひとつに", accent: "もっとシンプルに。", description: "画像・PDF・音声をインストールなしでブラウザ上ですぐに処理できます。", cta: "JPG PNG変換を開始", tools: "人気の画像ツール", privacy: "ファイルはブラウザ内で安全に処理されます。" },
  zh: { language: "简体中文", eyebrow: "OneDay Tools · All in One Tool", title: "文件处理，一站完成", accent: "简单又快速。", description: "无需安装，在浏览器中直接处理图片、PDF和音频文件。", cta: "开始 JPG 转 PNG", tools: "热门图片工具", privacy: "文件仅在浏览器中安全处理。" },
  "zh-tw": { language: "繁體中文", eyebrow: "OneDay Tools · All in One Tool", title: "檔案處理，一站完成", accent: "簡單又快速。", description: "無需安裝，直接在瀏覽器處理圖片、PDF 與音訊檔案。", cta: "開始 JPG 轉 PNG", tools: "熱門圖片工具", privacy: "檔案只會在瀏覽器中安全處理。" },
  de: { language: "Deutsch", eyebrow: "OneDay Tools · All in One Tool", title: "Dateien an einem Ort", accent: "Einfach erledigt.", description: "Bilder, PDFs und Audiodateien direkt im Browser bearbeiten – ohne Installation.", cta: "JPG in PNG umwandeln", tools: "Beliebte Bildwerkzeuge", privacy: "Ihre Dateien werden sicher im Browser verarbeitet." },
  fr: { language: "Français", eyebrow: "OneDay Tools · All in One Tool", title: "Vos fichiers, au même endroit", accent: "Tout simplement.", description: "Traitez vos images, PDF et fichiers audio directement dans le navigateur, sans installation.", cta: "Commencer JPG vers PNG", tools: "Outils d’image populaires", privacy: "Vos fichiers sont traités en toute sécurité dans votre navigateur." },
  es: { language: "Español", eyebrow: "OneDay Tools · All in One Tool", title: "Tus archivos en un solo lugar", accent: "Así de fácil.", description: "Procesa imágenes, PDF y audio directamente en el navegador, sin instalar nada.", cta: "Empezar JPG a PNG", tools: "Herramientas de imagen populares", privacy: "Tus archivos se procesan de forma segura en tu navegador." },
};
