import type { Locale } from "./i18n";

export const homeCopy: Record<Locale, { language: string; eyebrow: string; title: string; accent: string; description: string; cta: string; tools: string; privacy: string }> = {
  ko: { language: "한국어", eyebrow: "OneDay Tools · All in One Tool", title: "파일 작업을 한곳에서", accent: "더 간단하게.", description: "이미지·PDF·오디오 도구를 설치 없이 브라우저에서 바로 처리하세요.", cta: "JPG PNG 변환 시작", tools: "인기 이미지 도구", privacy: "파일은 브라우저 안에서 안전하게 처리됩니다." },
  en: { language: "English", eyebrow: "OneDay Tools · All in One Tool", title: "Handle files in one place", accent: "Keep it simple.", description: "Convert and manage images, PDFs, and audio right in your browser—no install required.", cta: "Start JPG to PNG", tools: "Popular image tools", privacy: "Your files are processed securely in your browser." },
  ja: { language: "日本語", eyebrow: "OneDay Tools · All in One Tool", title: "ファイル作業をひとつに", accent: "もっとシンプルに。", description: "画像・PDF・音声をインストールなしでブラウザ上ですぐに処理できます。", cta: "JPG PNG変換を開始", tools: "人気の画像ツール", privacy: "ファイルはブラウザ内で安全に処理されます。" },
  zh: { language: "简体中文", eyebrow: "OneDay Tools · All in One Tool", title: "文件处理，一站完成", accent: "简单又快速。", description: "无需安装，在浏览器中直接处理图片、PDF和音频文件。", cta: "开始 JPG 转 PNG", tools: "热门图片工具", privacy: "文件仅在浏览器中安全处理。" },
  "zh-tw": { language: "繁體中文", eyebrow: "OneDay Tools · All in One Tool", title: "檔案處理，一站完成", accent: "簡單又快速。", description: "無需安裝，直接在瀏覽器處理圖片、PDF 與音訊檔案。", cta: "開始 JPG 轉 PNG", tools: "熱門圖片工具", privacy: "檔案只會在瀏覽器中安全處理。" },
  de: { language: "Deutsch", eyebrow: "OneDay Tools · All in One Tool", title: "Dateien an einem Ort", accent: "Einfach erledigt.", description: "Bilder, PDFs und Audiodateien direkt im Browser bearbeiten – ohne Installation.", cta: "JPG in PNG umwandeln", tools: "Beliebte Bildwerkzeuge", privacy: "Ihre Dateien werden sicher im Browser verarbeitet." },
  fr: { language: "Français", eyebrow: "OneDay Tools · All in One Tool", title: "Vos fichiers, au même endroit", accent: "Tout simplement.", description: "Traitez vos images, PDF et fichiers audio directement dans le navigateur, sans installation.", cta: "Commencer JPG vers PNG", tools: "Outils d’image populaires", privacy: "Vos fichiers sont traités en toute sécurité dans votre navigateur." },
  es: { language: "Español", eyebrow: "OneDay Tools · All in One Tool", title: "Tus archivos en un solo lugar", accent: "Así de fácil.", description: "Procesa imágenes, PDF y audio directamente en el navegador, sin instalar nada.", cta: "Empezar JPG a PNG", tools: "Herramientas de imagen populares", privacy: "Tus archivos se procesan de forma segura en tu navegador." },
};
